### ISSUE TITLE
Change the sidebar chain numbering from alphabetical to para ID

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/polkadot_network_directory#22]
The current sidebar has auto-generated numbering based on the alphabetically sorted list of relay/para chains.
It would be more valuable to sort chains by their Para ID.

![Screenshot from 2022-12-07 17-39-41](https://user-images.githubusercontent.com/513471/206238363-1d0f4518-e930-448e-b3e5-1864e17fa5f9.png)

**Comment by chevdor** [comment]
I think we can solve the issue if we tweak or find a theme without those numbers for the list items.

**Comment by chevdor** [comment]
Partly fixed by #25 
<img width="195" alt="image" src="https://user-images.githubusercontent.com/738724/206673996-a1fc2bff-da94-47f3-b012-2b2de93c9dae.png">
