### ISSUE TITLE
Script to fetch documentation sites

### ISSUE THREAD

**Issue by sacha-l** [paritytech/polkadot_network_directory#38]
Having a portal with all documentation hubs from all chains in the ecosystem  has been something in the back of my mind for quite some time now. I believe the SubWallet (Dotinsights) team are working on providing something similar, though the challenge (as always) is how to maintain such a list and avoid unmaintained sites. 

I would love to see a script that can be used to fetch the `documentation` URLs  from the yaml files and parsed into a JSON and also checks when the last PR was merged to retrieve information about how up-to-date a referenced doc site is. Then it'd be easy to create a reasonably future Polkadot Developer Hub portal that lists all doc sites 💭.

**Comment by chevdor** [comment]
> I would love to see a script that can be used to ...

let see :)

> fetch the documentation URLs from the yaml files and parsed into a JSON 

this is trivial today using https://paritytech.github.io/polkadot_network_directory/chains.json and `jq`

> and also checks when the last PR was merged to retrieve information about how up-to-date a referenced doc site is.

I am not sure if this is doable. The `documentation` url could be anything. Some teams will point to a site generated by a static generator, some will point to a wiki or a git repo, it could also be a any kinda of site so there is no garanty we can find a date somewhere **in all of them** unless there is some kinda standard.

> Then it'd be easy to create a reasonably future Polkadot Developer Hub portal that lists all doc sites 💭.

Indeed.

**Comment by sacha-l** [comment]
Awesome, thanks for this @chevdor.

> I am not sure if this is doable. The documentation url could be anything. Some teams will point to a site generated by a static generator, some will point to a wiki or a git repo, it could also be a any kinda of site so there is no garanty we can find a date somewhere in all of them unless there is some kinda standard.

Right... The big challenge with this sort of initiative is to ensure data is up to date. For example, [this page](https://substrate.io/ecosystem/projects/) which is hard to maintain. How will this repo ensure that teams are providing the most updated details and that information doesn't get outdated?

**Comment by chevdor** [comment]
This repo cannot ensure this, it is left to each team to provide and update their data.
We do however how the reader when the site was refershed last.
