### ISSUE TITLE
Anagolay/Idiyanale Testnet information not showing up

### ISSUE THREAD

**Issue by joshuacheong** [paritytech/polkadot_network_directory#54]
Hey team, Anagolay team raise this PR but it did not seem to show up. Please help to troubleshoot. Thank you! 🙏🏻
- https://github.com/paritytech/polkadot_network_directory/pull/35/files

**Comment by chevdor** [comment]
One issue I see already is that `Idiyanale Testnet` is defined with a parent: `Anagolay` which in turn is not defined. It does not make sense for a solo testnet to have parent defined.
