### ISSUE TITLE
Add whether TLS is installed for light client support

### ISSUE THREAD

**Issue by sacha-l** [paritytech/polkadot_network_directory#55]
A useful piece of information that seems to me missing is whether a parachain has a TLS certificate installed in order to use a parachain chainspec using substrate connect in an application. Without TLS certificates Substrate Connect doesn't work AFAIK.

This would allow developers to know which chains they can use for connecting their app to a light client.

cc @wirednkod (may have more context here).

**Comment by wirednkod** [comment]
Actually once [this](https://github.com/paritytech/substrate/pull/12529) is merged - and Smoldot and Substrate connect starts fully supporting WebRTC then this will not be needed
