### ISSUE TITLE
Rename Statemine / Statemint to Assets Hub

### ISSUE THREAD

**Issue by sacha-l** [paritytech/polkadot_network_directory#61]
As per https://github.com/paritytech/cumulus/issues/2591 we will be renaming Statemine to "Kusama Asset Hub" and Statemint to "Polkadot Asset Hub".

These pages should be updated accordingly once this change is enacted:

- https://paritytech.github.io/polkadot_network_directory/chains/Polkadot/Statemint.html
- https://paritytech.github.io/polkadot_network_directory/chains/Kusama/Statemine.html

**Comment by chevdor** [comment]
PR Welcome 😄

**Comment by PierreBesson** [comment]
New RPC endpoints are available while the old one will still be accessible. See: https://github.com/polkadot-js/apps/pull/9526

**Comment by chevdor** [comment]
Related: https://github.com/paritytech/polkadot_network_directory/pull/62
