### ISSUE TITLE
Run RPC endpoint daily validity checks

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/polkadot_network_directory#68]
To make sure our RPC endpoints are available, we should run daily checks using Github Action.

http check:
```
curl -sS -X POST  -H "Content-Type: application/json"  -d '{"id":1,"jsonrpc":"2.0","method":"system_version"}' https://rpc.polkadot.io
```

ws check:
```
echo '{"id":1,"jsonrpc":"2.0","method":"rpc_methods","params":[]}' | websocat -n1 -B 99999999 wss://rpc.polkadot.io
```

In case a failure is detected, we could automatically create an issue (as is done in polkadot.js https://github.com/polkadot-js/apps/blob/master/.github/workflows/chain-endpoints.yml) or we could automatically commit a `valid=true|false`,eg:

```
rpc_endpoints:
  - name: Parity
    url: wss://rpc.polkadot.io:443
    valid: true
```

This would then display as ✅ or ❌ in the website.

**Comment by chevdor** [comment]
I really like the idea, however, I think this should be the work of `subrpc` (it was designed for that).

The fact that GH sees a endpoint down does not have to mean the endpoint is actually down for a given user.
Some endpoints maybe blocking some regions for instance. 

Also, `valid` or not should probably not be based on a single (even daily) check. For instance, if a check fails today but the endpoint was up the last 100 days, we could keep it in the list.

That being said, I think your approach would be good as step #1
