### ISSUE TITLE
Publish RPC endpoints list in an npm package

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/polkadot_network_directory#71]
To be easily consumed by dapps, it would be ideal if the list could be published in an npm package.

**Comment by chevdor** [comment]
that's a great idea

**Comment by rossbulat** [comment]
npm package should be the primary delivery method if this is aimed for Dapps, with a secondary public endpoint, e.g. a http and ipfs url that points directly to the data.

Myself and @wirednkod are consolidating static assets under a `@polkadot-cloud/assets` package that is documented on  https://polkadot.cloud/ . It makes sense to me to package this resource up under `@polkadot-cloud/assets/endpoints`. We could perhaps set up some automation to source this repo to construct the package on the cloud side.

**Comment by wirednkod** [comment]
This is already part of my TO-DO list and will probably get onto it next week.
Here is an issue for tracking: https://github.com/paritytech/polkadot-cloud/issues/756

**Comment by wirednkod** [comment]
For having only a single point of truth, I created a script that retrieves the YAML information, converts it to JSON and then publish them under `@polkadot-cloud/assets` package

**Comment by chevdor** [comment]
Why not using the json generated [here](https://paritytech.github.io/polkadot_network_directory/chains.json) ?

**Comment by wirednkod** [comment]
> Why not using the json generated [here](https://paritytech.github.io/polkadot_network_directory/chains.json) ?

1) I am converting from yaml and checking against an interface the values
2) what you point at is 1 big fat json while I prefer to have JSON split by network name and export separately (as YAML are);

**Comment by PierreBesson** [comment]
@wirednkod if you would like to collaborate on this, we could merge the polkadot_network_directory project into polkadot-cloud:
This would have: 
- an easy way to contribute info in YAML files for each chain directly in the polkadot-cloud repo. This will include a list of RPC and bootnodes (substrate-connect) for each chain.
- validation of contributed data with YAML schema (with @chevdor's yamlcheck tooln, see https://github.com/paritytech/polkadot_network_directory/blob/master/scripts/check_all.sh)

I think @chevdor and me would be satisfied to remove this repo in favor of yours as long as we can have the publication of JSON and HTML files for each chain on `polkadot.cloud`.

I think collaborating on this would be highly beneficial for the ecosystem and give people a better network directory than what is currently provided by polkadot.js in a place where they can easily find it (as we have failed to drive significant contributions to this repo).

**Comment by wirednkod** [comment]
Thank you @PierreBesson . I would love to colab on this. I will contact you and/or @chevdor in order to make sure I understand all parts that should be transferred to polkadot-cloud

**Comment by chevdor** [comment]
Indeed, the core job of this repo is:
- collect data about chains as simply as possible, without assumption about how this data will be used. The raw data being available, each consumer can decide what is relevant and what is not.
- process this data to make it consumable for:
  - tools (via generation of the json file)
  - humans (via the markdown book)

The idea is also to keep the repo "neutral" and not aiming at being for one specific need such as a UI lib.

Using the data (and/or reprocessing it as it is being done) is totally fine (and that's the goal) but I am not convinced it makes it easier for external contributors to pull a UI library repo to contribute data about (para)chains. That would be doing what it done sofar with PJS, just in another repo so I don't see much benefit.
